// App version shown in Settings. Bump together with VERSION in sw.js ("rb-v" + APP_VERSION).
export const APP_VERSION = 20;
export const RELEASED = "2026-10-02";
export const WHATS_NEW = [
  "Oat, almond and soy milk (or whole, 2% and skim) stay separate lines on the grocery list.",
  "\"half and half\" is read as the cream, and amounts like \"1,000 g\" or \"1,5 kg\" work.",
  "Reloading for an update no longer loses text you're typing in another tab.",
  "Adding \"ice cream\", \"garlic bread\" or \"salt and vinegar chips\" now adds them (they no longer count as cream, garlic or vinegar), in the right aisle. New Snacks and Drinks aisles.",
  "The same thing added on two phones at once ends up as one line.",
  "Store aisles: drag by the ≡ handle and scroll anywhere else; the list follows as you go.",
  "Grocery rows: names get the room, package sizes sit on a small second line.",
  "Opens instantly even with a weak signal; updates download in the background (\"Recipe Box updated · Reload\").",
  "The recipe book opens much faster with a big library.",
  "A calmer, roomier look everywhere, with the pixel icons kept as accents. Works in light and dark.",
  "Grocery list: tap a row to check it off; it folds into In cart, with Undo. Press and hold, or swipe left, for details.",
  "Fast add: type \"2 lb chicken thighs\" and it lands in the right aisle. Suggestions and chips come from what you usually buy, and repeats merge.",
  "Things you add stay on one household list, so they don't disappear when the week changes.",
  "Stores: drag the aisles into the order you walk them.",
  "Shopping mode: bigger rows, only what's left, and the screen stays on. Done shopping clears what you bought.",
  "See your partner's changes within seconds: \"Emma checked eggs\".",
  "A spoonful of granola or miso now shows as one bag or tub, not \"2 tbsp\".",
  "Add from a link or Siri: …/recipes/?add=milk, eggs (see the README for the iOS Shortcut).",
  "Shared ratings: everyone rates recipes themselves and the average is what shows. Set your name in Settings → Sync.",
  "Planning together: meals added, moved or removed on two phones at once all stick, and recipe edits (rating on one phone, notes on the other) both keep.",
  "\"half a dozen eggs\", \"2 + 1/2 cups\" and the grocery list's \"2 dozen (24 eggs)\" now read right.",
  "Recipe links are read by your Worker, which sends back just the recipe (faster, and the Worker can't be used as a proxy).",
  "Shopping together: checking items on two phones at once no longer undoes each other, and checks show up within seconds.",
  "Restoring a backup keeps anything newer (Merge), or replaces everything only when you say so.",
  "Better ingredient reading: \"1 dozen eggs\", \"2 x 400g tins\", \"1 tbsp + 1 tsp\"; \"large onion\" keeps its size; US amounts like \"½ cup + 1 tbsp\".",
  "\"20 to 25 minutes\" offers both timers; finished timers say how long ago.",
  "After saving a recipe, you're asked once to fill in nutrition or prices the app doesn't know. Change them anytime with Ingredient info.",
  "Price per serving has its own line on every recipe card.",
  "Tapped recipes no longer stay highlighted on iPhone.",
  "New font: Nunito, easier to read. The 8-bit icons stay.",
  "Official U.S. grocery prices (BLS) and USDA nutrition through your Worker.",
  "One-time sync invites: each code works once and expires after 24 hours.",
  "Edit grocery items and recipe ingredients; add-to-list is at the top."
];
