// App version shown in Settings. Bump together with VERSION in sw.js ("rb-v" + APP_VERSION).
export const APP_VERSION = 37;
export const RELEASED = "2026-10-06";
export const WHATS_NEW = [
  "Anonymous crash reports and usage stats, so problems get found and fixed: which version broke, and whether planning, shopping and cooking work as they should. Never your recipes, ingredients, lists, notes, prices or anything you type, and no names or email. Turn it off in Settings, under Privacy.",
  "After cooking a planned meal, leaving cook mode asks \"Done cooking?\" (only while usage stats are on).",
  "Joining a partner's recipe box is easier: on a new phone, paste the invite link in Settings, under Sync, and tap Join. It works from the app on your Home Screen, and brings everything the phone needs to sync.",
  "Buttons next to a text box (like Join or Add) work on the first tap while the keyboard is up.",
  "A fresh look: one set of pixel icons throughout, shorter and plainer wording, and tips that show once instead of instructions everywhere.",
  "Imported recipes show where they're from, with View original. Recipes read automatically from a page or a photo say so, so you know to check them.",
  "Nutrition and costs are clearly estimates: a one-time note, an Estimates button by Nutrition and Cost, and About estimates in Settings. Recipes say how many ingredients are matched and how many are estimated.",
  "\"Low cal\" is now \"Lighter\".",
  "Still need these? only offers things you added yourself, unticked, so you tap what you still need.",
  "Text follows your phone's text size, and Settings has a Text size option. Zoom is off, and buttons are easier to tap.",
  "Store-bought meals: plan a Trader Joe's lunch (or any ready-made meal) like a recipe. In the meal plan's recipe picker, tap + Store-bought meal: name, store, servings and price, and paste a picture of the label for its nutrition. It goes on the grocery list as whole packages under Prepared foods, and counts toward the day's calories and the week's food cost. Find them in Recipes with the Store-bought chip.",
  "Grocery list: after you stop shopping, what you checked off is under \"Purchased\" (it's \"In cart\" while you shop).",
  "\"Green onions (white parts only)\" is just green onions on the list, not \"white green onions\".",
  "Fewer \"Shake to Undo\" pop-ups while shopping: the add box forgets your typing once you leave it.",
  "Sheets (like picking a recipe for the meal plan) respond to taps and scroll on their own; the page behind them stays put.",
  "While you're typing, the tab bar and Start shopping step aside instead of floating over the list.",
  "Nutrition labels: Paste label image reads a copied picture of the label (a screenshot, or in Photos: Share, then Copy Photo). In the \"Fill in missing info?\" prompt it fills in that ingredient's numbers right there, without leaving the prompt; Save keeps it as the product's label.",
  "The app opens on Today again, with Today on the left of the Today | Week switch.",
  "Recipe photos no longer blink when you switch pages.",
  "The week's meal plan is the first page again, and Plan is the first tab. Today is one tap away (Week | Today).",
  "Recipes: a Filters button next to search has everything you can filter by: meal, calories, protein, time and cost per serving, rating and keywords. The quick filters stay along the top.",
  "Recipes you saved before photos get theirs automatically, a few at a time while the recipe book is open.",
  "More: the arrows line up on the right, with room between each name and its note.",
  "A tab bar at the bottom: Recipes, Plan, List and More. The app opens on Today: tonight's dinner (Start cooking opens it in cook mode), the day's other meals, the grocery list and tomorrow. Week is one tap away.",
  "More holds Pantry, Prices, Stores & aisles, the unit converter, Sync, Settings and Backup.",
  "Recipe pages: Edit, Share and Delete live under the More button, so Delete is never one stray tap away.",
  "Recipe photos: recipes added from a link get the site's photo on the recipe, the book and Today. Older recipes: More, then Get photo. Photos stay on each phone (they aren't synced).",
  "Grocery list: specific products from recipes get their own line (protein pasta and pasta, skim and whole milk). A recipe that just says \"butter\" shares the \"unsalted butter\" line.",
  "Recipes: when protein pasta (or another big ingredient) is using regular pasta's numbers, a quiet note under Nutrition says so, with Add its label. Ingredients with no nutrition get the same note, so the fill-in form is always one tap away.",
  "Nutrition labels: \"56 Gram\" and ounce-only serving sizes are read.",
  "The recipe book opens faster.",
  "Every page has its title next to the back arrow, laid out like the grocery list.",
  "Accessibility: pinch to zoom works again (double-tap still doesn't zoom), gray text is easier to read, and the Settings fields are labeled for VoiceOver.",
  "\"Hot dogs\" are hot dogs.",
  "Shopping mode keeps the title, store and week at the top (they scroll away), so the first items are in easy reach; the progress bar stays pinned.",
  "Grocery lists start fresh every week. Things last week's list didn't get to are offered once on this week's list: \"Still need these?\" Add to this week, or Start fresh. (Skipped it by mistake? \"From last week\" at the bottom of the list brings it back.)",
  "Settings, Shopping & prep day: your week runs from the next day, and the grocery list starts fresh on it. The meal plan, lists and everything already planned follow, on both phones.",
  "Grocery list: about twice as many items fit on screen. Groceries and the store button share the top line, the item count sits beside the week, and rows (and the add box) are a little shorter. Your usual-item chips appear when you tap into the add box.",
  "Shopping mode goes full screen: same-size rows as the list, with a progress bar and \"X of Y\" pinned at the top. Stop shopping takes you back to the list, with what you got folded under In cart.",
  "New font: IBM Plex Sans.",
  "The app no longer zooms when you pinch or double-tap, like a regular iPhone app.",
  "Specific products (protein pasta, chickpea pasta, a brand) are their own ingredient instead of silently using regular pasta's numbers.",
  "Optional: in a recipe's Nutrition section, tap an ingredient to scan or paste its Nutrition Facts label. Every recipe with it gets exact numbers, on every synced phone.",
  "Recipes: your rating is the big row of stars you tap; the household average is a small line under it.",
  "New Settings icon (two switches), and the grocery list icon has room under its last line.",
  "Recipe book: cards no longer list keywords; search and the filter chips still use them.",
  "Prices and nutrition drop the ~ in front of every number.",
  "Oat, almond and soy milk (or whole, 2% and skim) stay separate lines on the grocery list. Adding \"2% milk\" when a recipe needs milk offers Use for recipe.",
  "\"half and half\" is read as the cream, and amounts like \"1,000 g\" or \"1,5 kg\" work.",
  "Reloading for an update no longer loses text you're typing in another tab.",
  "Adding \"ice cream\", \"garlic bread\" or \"salt and vinegar chips\" now adds them (they no longer count as cream, garlic or vinegar), in the right aisle. New Snacks and Drinks aisles.",
  "The same thing added on two phones at once ends up as one line.",
  "Store aisles: drag by the handle and scroll anywhere else; the list follows as you go.",
  "Grocery rows: names get the room, package sizes sit on a small second line.",
  "Opens instantly even with a weak signal; updates download in the background (\"Recipe Box updated\" with Reload).",
  "The recipe book opens much faster with a big library.",
  "A calmer, roomier look everywhere, with the pixel icons kept as accents. Works in light and dark.",
  "Grocery list: tap a row to check it off; it folds into In cart, with Undo. Press and hold, or swipe left, for details.",
  "Fast add: type \"2 lb chicken thighs\" and it lands in the right aisle. Suggestions and chips come from what you usually buy, and repeats merge.",
  "Things you add stay on one household list, so they don't disappear when the week changes.",
  "Stores: drag the aisles into the order you walk them.",
  "Shopping mode: bigger rows, only what's left, and the screen stays on. Done shopping clears what you bought.",
  "See your partner's changes within seconds: \"Emma checked eggs\".",
  "A spoonful of granola or miso now shows as one bag or tub, not \"2 tbsp\".",
  "Add from a link or Siri: …/recipes/?add=milk, eggs (see the README for the iOS Shortcut).",
  "Shared ratings: everyone rates recipes themselves and the average is what shows. Set your name in Settings, under Sync.",
  "Planning together: meals added, moved or removed on two phones at once all stick, and recipe edits (rating on one phone, notes on the other) both keep.",
  "\"half a dozen eggs\", \"2 + 1/2 cups\" and the grocery list's \"2 dozen (24 eggs)\" now read right.",
  "Recipe links are read by your Worker, which sends back just the recipe (faster, and the Worker can't be used as a proxy).",
  "Shopping together: checking items on two phones at once no longer undoes each other, and checks show up within seconds.",
  "Restoring a backup keeps anything newer (Merge), or replaces everything only when you say so.",
  "Better ingredient reading: \"1 dozen eggs\", \"2 x 400g tins\", \"1 tbsp + 1 tsp\"; \"large onion\" keeps its size; US amounts like \"½ cup + 1 tbsp\".",
  "\"20 to 25 minutes\" offers both timers; finished timers say how long ago.",
  "After saving a recipe, you're asked once to fill in nutrition or prices the app doesn't know. Change them anytime with Ingredient info.",
  "Price per serving has its own line on every recipe card.",
  "Tapped recipes no longer stay highlighted on iPhone.",
  "New font: Nunito, easier to read. The 8-bit icons stay.",
  "Official U.S. grocery prices (BLS) and USDA nutrition through your Worker.",
  "One-time sync invites: each code works once and expires after 24 hours.",
  "Edit grocery items and recipe ingredients; add-to-list is at the top."
];
